# Generated by Django 4.2.19 on 2025-03-09 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0002_votes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Votes',
        ),
    ]
