# Generated by Django 4.2.19 on 2025-03-09 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_room_current_song'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='current_song',
        ),
    ]
